import { useEffect, useMemo, useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { ArrowLeft, ArrowRight, Brain, ChevronDown, ChevronUp, Expand, Minimize2, Target } from 'lucide-react'

type Kind='cover'|'mental'|'cognitive'|'hick'|'fitts'|'jakob'|'restorff'|'recognition'|'disclosure'|'peak'|'real'|'activity'|'summary'
type Slide={kicker:string,title:string,subtitle:string,theory:string,definition?:string,type:Kind}

const slides:Slide[]=[
{kicker:'Interfaz de Usuario · UX/UI',title:'La psicología detrás de una interfaz',subtitle:'Cómo nuestra percepción y nuestras decisiones condicionan el diseño UX/UI.',theory:'El usuario llega a cada interfaz con atención limitada, memoria limitada, hábitos y expectativas previas. Diseñar bien implica comprender cómo percibe, decide y recuerda.',type:'cover'},
{kicker:'1 · Modelos mentales',title:'El usuario usa lo que cree que entiende',subtitle:'Las personas interpretan una interfaz a partir de experiencias previas.',definition:'Modelo mental: representación interna que una persona construye sobre cómo cree que funciona un sistema.',theory:'Cuando una interfaz coincide con el modelo mental del usuario se aprende más rápido. Si lo contradice sin motivo, aumenta la fricción.',type:'mental'},
{kicker:'2 · Carga cognitiva',title:'La interfaz también puede cansar',subtitle:'La dificultad no siempre está en la tarea; muchas veces está en cómo se presenta.',definition:'Carga cognitiva: esfuerzo mental necesario para comprender información, tomar decisiones y completar una tarea.',theory:'Demasiadas opciones, baja jerarquía o pasos mal organizados obligan al usuario a pensar más de lo necesario.',type:'cognitive'},
{kicker:'3 · Ley de Hick',title:'Más opciones pueden significar más tiempo de decisión',subtitle:'No siempre dar más alternativas ayuda.',definition:'Ley de Hick: el tiempo de decisión tiende a aumentar cuando crece la cantidad o complejidad de alternativas.',theory:'Agrupar, jerarquizar y priorizar alternativas puede reducir el esfuerzo de elección.',type:'hick'},
{kicker:'4 · Ley de Fitts',title:'Un objetivo pequeño y lejano cuesta más',subtitle:'El tamaño y la distancia afectan la facilidad de interacción.',definition:'Ley de Fitts: alcanzar un objetivo suele ser más fácil cuando es grande y se encuentra a una distancia razonable.',theory:'En UI se traduce en targets táctiles cómodos y acciones frecuentes ubicadas en zonas accesibles.',type:'fitts'},
{kicker:'5 · Ley de Jakob',title:'Los usuarios pasan más tiempo en otras interfaces que en la nuestra',subtitle:'Las convenciones permiten aprovechar aprendizaje previo.',definition:'Ley de Jakob: los usuarios esperan que una interfaz funcione de manera similar a otras que ya conocen.',theory:'Respetar patrones conocidos no es copiar sin criterio: es reducir el costo de aprendizaje.',type:'jakob'},
{kicker:'6 · Von Restorff',title:'Lo diferente llama la atención',subtitle:'El contraste puede dirigir la mirada, pero debe usarse con intención.',definition:'Efecto Von Restorff: entre elementos similares, el diferente tiende a captar más atención y recordarse mejor.',theory:'Si todo está destacado, el destaque deja de tener significado.',type:'restorff'},
{kicker:'7 · Reconocimiento vs recuerdo',title:'Es más fácil reconocer que recordar desde cero',subtitle:'Una interfaz no debería obligar al usuario a memorizar demasiado.',definition:'Reconocimiento: identificar algo visible. Recuerdo: recuperar información sin ayuda externa.',theory:'Menús, sugerencias, historial e íconos con texto reducen la dependencia de la memoria.',type:'recognition'},
{kicker:'8 · Progressive Disclosure',title:'Mostrar lo necesario en el momento adecuado',subtitle:'No todo lo que existe debe mostrarse al mismo tiempo.',definition:'Progressive Disclosure: mostrar primero lo principal y revelar opciones adicionales cuando sean necesarias.',theory:'Reduce carga cognitiva y mantiene legibles interfaces complejas.',type:'disclosure'},
{kicker:'9 · Peak-End Rule',title:'La experiencia se recuerda por momentos clave y por cómo termina',subtitle:'El cierre de una tarea puede dominar el recuerdo final.',definition:'Peak-End Rule: las personas tienden a recordar una experiencia por sus momentos más intensos y por su final.',theory:'Un flujo correcto puede dejar mala impresión si termina con un error confuso; un cierre claro reduce incertidumbre.',type:'peak'},
{kicker:'10 · Ejemplos reales',title:'Estos principios aparecen en interfaces cotidianas',subtitle:'Menús, botones, formularios y mensajes contienen decisiones psicológicas.',theory:'El objetivo es usar los principios como herramientas para analizar y justificar mejoras concretas.',type:'real'},
{kicker:'Actividad',title:'Mini laboratorio de psicología UX',subtitle:'Analizar una pantalla y defender un rediseño con vocabulario técnico.',theory:'Detectar tres principios, identificar una fricción y proponer una mejora justificada.',type:'activity'},
{kicker:'Cierre',title:'Diseñar interfaces es diseñar decisiones',subtitle:'Una buena UI ayuda a percibir, decidir, comprender y recordar mejor.',theory:'Diseñar bien significa reducir fricción respetando cómo realmente funcionan la atención, la memoria y las expectativas humanas.',type:'summary'}]

const Btn=({children,onClick,kind='primary',active=false}:{children:React.ReactNode,onClick?:()=>void,kind?:'primary'|'secondary'|'danger'|'success',active?:boolean})=><motion.button whileHover={{y:-2,scale:1.02}} whileTap={{scale:.96}} onClick={onClick} className={`btn ${kind} ${active?'active':''}`}>{children}</motion.button>

function Cover(){return <div className="cover"><div className="ring r1"/><div className="ring r2"/><motion.div className="brain" animate={{y:[0,-7,0],rotate:[0,2,-2,0]}} transition={{repeat:Infinity,duration:6}}><Brain size={70}/><b>UX<br/>Psychology</b></motion.div><span className="chip c1">Atención limitada</span><span className="chip c2">Memoria limitada</span><span className="chip c3">Expectativas</span><span className="chip c4">Decisiones</span></div>}
function Mental(){const[f,setF]=useState(true);return <div className="stack"><div className="seg"><Btn active={f} onClick={()=>setF(true)}>Convención familiar</Btn><Btn kind="secondary" active={!f} onClick={()=>setF(false)}>Convención rota</Btn></div><div className="window"><div className="header"><b>Aula Virtual</b><div className="icons"><button>{f?'🔍':'🗑️'}</button><button>{f?'👤':'🔍'}</button><button>{f?'🏠':'⚙️'}</button></div></div><div className={`feedback ${f?'good':'bad'}`}>{f?'El usuario puede transferir conocimiento previo.':'El usuario debe reaprender significados y pierde previsibilidad.'}</div></div></div>}
function Cognitive(){const[s,setS]=useState(false);const fs=['Nombre','Apellido','DNI','Email','Teléfono','Localidad','Provincia','País','Domicilio','Código postal','Materia','Comisión'];return <div className="stack"><div className="seg"><Btn kind="secondary" active={!s} onClick={()=>setS(false)}>Formulario cargado</Btn><Btn active={s} onClick={()=>setS(true)}>Por pasos</Btn></div><div className="formbox">{!s?<div className="gridform">{fs.map(x=><label key={x}>{x}<input/></label>)}</div>:<div className="step"><small>Paso 1 de 3 · Datos personales</small>{['Nombre','Apellido','DNI'].map(x=><label key={x}>{x}<input/></label>)}<Btn>Continuar →</Btn></div>}</div><em>Misma información posible, distinta carga percibida.</em></div>}
function Hick(){const[m,setM]=useState(false);const[sel,setSel]=useState('');const xs=m?['Inicio','Materias','Calendario','Mensajes','Notas','Profesores','Horarios','Biblioteca','Recursos','Perfil','Ayuda','Foros']:['Inicio','Materias','Perfil'];return <div className="stack"><div className="seg"><Btn active={!m} onClick={()=>{setM(false);setSel('')}}>3 opciones</Btn><Btn kind="secondary" active={m} onClick={()=>{setM(true);setSel('')}}>12 opciones</Btn></div><div className="choice"><h3>Elegí rápido dónde entrarías para ver una materia</h3><div>{xs.map((x,i)=><motion.button initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={{delay:i*.025}} key={x} onClick={()=>setSel(x)} className={sel===x?'picked':''}>{x}</motion.button>)}</div>{sel&&<p>Elegiste: <b>{sel}</b></p>}</div></div>}
function Fitts(){const[s,setS]=useState({a:0,b:0,c:0});return <div className="stack"><div className="targets"><button className="tiny" onClick={()=>setS(v=>({...v,a:v.a+1}))}>×</button><button className="medium" onClick={()=>setS(v=>({...v,b:v.b+1}))}>Medio</button><button className="large" onClick={()=>setS(v=>({...v,c:v.c+1}))}>CONTINUAR</button></div><div className="scores"><span>Pequeño <b>{s.a}</b></span><span>Medio <b>{s.b}</b></span><span>Grande <b>{s.c}</b></span></div><em>Pediles que hagan click rápido sobre diferentes objetivos.</em></div>}
function Jakob(){const[w,setW]=useState(false);return <div className="stack"><div className="seg"><Btn active={!w} onClick={()=>setW(false)}>Convenciones</Btn><Btn kind="danger" active={w} onClick={()=>setW(true)}>Invertir símbolos</Btn></div><div className="jakob"><div><span>{w?'🗑️':'🔍'}</span><b>Buscar</b></div><div><span>{w?'🔍':'🗑️'}</span><b>Eliminar</b></div><div><span>{w?'⚙️':'🏠'}</span><b>Inicio</b></div></div><div className={`feedback ${w?'bad':'good'}`}>{w?'La etiqueta aclara, pero la primera lectura visual ya genera conflicto.':'El patrón coincide con lo que el usuario espera.'}</div></div>}
function Restorff(){const[s,setS]=useState(true);return <div className="stack"><div className="seg"><Btn active={s} onClick={()=>setS(true)}>Un destacado</Btn><Btn kind="secondary" active={!s} onClick={()=>setS(false)}>Todo destacado</Btn></div><div className="rest">{Array.from({length:12}).map((_,i)=><motion.div whileHover={{scale:1.06}} key={i} className={(s?i===6:true)?'hot':''}>{i===6?'TP':'Item'}</motion.div>)}</div><em>Preguntá primero: “¿Dónde miraron?”</em></div>}
function Recognition(){const[m,setM]=useState<'recognition'|'recall'>('recognition');return <div className="stack"><div className="seg"><Btn active={m==='recognition'} onClick={()=>setM('recognition')}>Reconocimiento</Btn><Btn kind="secondary" active={m==='recall'} onClick={()=>setM('recall')}>Recuerdo</Btn></div><div className="recog">{m==='recognition'?<><h3>¿Dónde buscarías una actividad pendiente?</h3><div>{['📚 Materias','🗓️ Calendario','✅ Actividades','👤 Perfil'].map(x=><button key={x}>{x}</button>)}</div></>:<div className="recall"><h3>Escribí el nombre exacto del módulo donde se consultan entregas</h3><input placeholder="¿Cómo se llamaba...?"/><p>Ahora no hay opciones visibles que ayuden a reconocer.</p></div>}</div></div>}
function Disclosure(){const[o,setO]=useState(false);return <div className="stack"><div className="settings"><h3>Configuración</h3>{['Cuenta','Notificaciones','Privacidad'].map(x=><div key={x}>{x}</div>)}<button className="advanced" onClick={()=>setO(!o)}>Opciones avanzadas {o?<ChevronUp size={18}/>:<ChevronDown size={18}/>}</button><AnimatePresence>{o&&<motion.section initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}}><span>Exportar datos</span><span>Permisos experimentales</span><span>Configuración técnica</span></motion.section>}</AnimatePresence></div><em>La complejidad existe, pero no invade la primera lectura.</em></div>}
function Peak(){const[g,setG]=useState(false);return <div className="stack"><div className="seg"><Btn kind="danger" active={!g} onClick={()=>setG(false)}>Final confuso</Btn><Btn kind="success" active={g} onClick={()=>setG(true)}>Final claro</Btn></div><div className="journey">{['Inicio','Datos','Confirmar'].map(x=><div key={x}>{x}</div>)}<motion.div key={String(g)} initial={{scale:.9,opacity:0}} animate={{scale:1,opacity:1}} className={g?'ok':'error'}>{g?'Entrega enviada ✓':'ERROR 0x409'}</motion.div></div><div className={`feedback ${g?'good':'bad'}`}>{g?'El cierre confirma el resultado y reduce incertidumbre.':'El final puede dominar el recuerdo de todo el recorrido.'}</div></div>}
function Real(){return <div className="reallist">{[['Menú con 18 opciones','Hick + carga cognitiva'],['Botón principal grande','Fitts'],['Lupa para buscar','Jakob + modelo mental'],['CTA único destacado','Von Restorff'],['Historial visible','Reconocimiento'],['Opciones avanzadas ocultas','Progressive Disclosure']].map(([a,b],i)=><motion.div key={a} initial={{opacity:0,x:25}} animate={{opacity:1,x:0}} transition={{delay:i*.05}}><b>{a}</b><span>{b}</span></motion.div>)}</div>}
function Activity(){return <div className="activity">{['Elegir una pantalla real o un prototipo de Figma.','Detectar tres principios psicológicos.','Marcar una decisión que aumente fricción.','Proponer una mejora usando vocabulario técnico.','Defender el cambio frente al curso.'].map((x,i)=><motion.div key={x} initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} transition={{delay:i*.06}}><span>{i+1}</span><b>{x}</b></motion.div>)}</div>}
function Summary(){return <div className="summary"><Target size={84}/><b>Una interfaz guía decisiones</b><span>Si entendemos cómo percibe y decide el usuario, podemos diseñar experiencias más claras, rápidas y predecibles.</span></div>}
function Visual({type}:{type:Kind}){if(type==='cover')return <Cover/>;if(type==='mental')return <Mental/>;if(type==='cognitive')return <Cognitive/>;if(type==='hick')return <Hick/>;if(type==='fitts')return <Fitts/>;if(type==='jakob')return <Jakob/>;if(type==='restorff')return <Restorff/>;if(type==='recognition')return <Recognition/>;if(type==='disclosure')return <Disclosure/>;if(type==='peak')return <Peak/>;if(type==='real')return <Real/>;if(type==='activity')return <Activity/>;return <Summary/>}

export default function App(){const[i,setI]=useState(0),[dir,setDir]=useState(1),[full,setFull]=useState(false);const s=slides[i];const prog=useMemo(()=>((i+1)/slides.length)*100,[i]);const go=(n:number)=>{const x=Math.max(0,Math.min(slides.length-1,n));setDir(x>=i?1:-1);setI(x)};const next=()=>go(i+1),prev=()=>go(i-1);const toggle=async()=>{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen()};useEffect(()=>{const f=()=>setFull(!!document.fullscreenElement);document.addEventListener('fullscreenchange',f);return()=>document.removeEventListener('fullscreenchange',f)},[]);useEffect(()=>{const k=(e:KeyboardEvent)=>{if(['ArrowRight','PageDown',' '].includes(e.key)){e.preventDefault();next()}if(['ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();prev()}if(e.key==='Home')go(0);if(e.key==='End')go(slides.length-1);if(e.key.toLowerCase()==='f')toggle()};window.addEventListener('keydown',k);return()=>window.removeEventListener('keydown',k)},[i]);return <main className="presentation"><div className="ambient a"/><div className="ambient b"/><header><div className="brand"><span><Brain size={22}/></span><div><b>Interfaz de Usuario</b><small>La psicología detrás de una interfaz</small></div></div><div className="actions"><b>{String(i+1).padStart(2,'0')} / {slides.length}</b><button onClick={toggle}>{full?<Minimize2 size={18}/>:<Expand size={18}/>} F</button></div></header><div className="progress"><motion.div animate={{width:`${prog}%`}}/></div><section className="stage"><AnimatePresence mode="wait" custom={dir}><motion.article key={i} custom={dir} variants={{enter:(d:number)=>({opacity:0,x:d>0?80:-80,scale:.985}),center:{opacity:1,x:0,scale:1},exit:(d:number)=>({opacity:0,x:d>0?-70:70,scale:.985})}} initial="enter" animate="center" exit="exit" transition={{duration:.42,ease:[.22,1,.36,1]}} className="slide"><div className="copy"><div className="kicker">{s.kicker}</div><h1>{s.title}</h1><p className="subtitle">{s.subtitle}</p>{s.definition&&<div className="definition"><span>Definición</span><p>{s.definition}</p></div>}<div className="theory"><span>Concepto para estudiar</span><p>{s.theory}</p></div></div><div className="visual"><Visual type={s.type}/></div></motion.article></AnimatePresence></section><footer><button onClick={prev} disabled={i===0}><ArrowLeft size={18}/>Anterior</button><div className="dots">{slides.map((_,x)=><button key={x} onClick={()=>go(x)} className={x===i?'active':''}/>)}</div><button onClick={next} disabled={i===slides.length-1}>Siguiente<ArrowRight size={18}/></button></footer></main>}
