import {useEffect,useMemo,useState} from 'react'
import {AnimatePresence,motion} from 'framer-motion'
import {ArrowLeft,ArrowRight,Blocks,Check,Component,Copy,Expand,Layers3,LayoutDashboard,Minimize2,Palette,PanelLeft,RefreshCw,Settings2,Sparkles,Type,Users,Workflow,X} from 'lucide-react'

type SlideType='cover'|'problem'|'definition'|'layers'|'component'|'instance'|'variants'|'states'|'nested'|'sidebar'|'tokens'|'consistency'|'scale'|'uikit'|'documentation'|'workflow'|'practice'|'summary'
type Slide={kicker:string,title:string,body:string,type:SlideType}

const slides:Slide[]=[
{kicker:'Interfaz de Usuario · Segundo cuatrimestre',title:'Design Systems',body:'De diseñar pantallas aisladas a construir un sistema de componentes reutilizables, coherentes y escalables.',type:'cover'},
{kicker:'01 · El problema',title:'¿Qué pasa si diseñamos cada pantalla desde cero?',body:'Copiar y pegar parece rápido al principio. El problema aparece cuando la interfaz crece y necesitamos mantener decenas de elementos repetidos.',type:'problem'},
{kicker:'02 · Definición',title:'¿Qué es un Design System?',body:'Es un conjunto organizado de principios, reglas, estilos, componentes y patrones reutilizables que permiten diseñar interfaces de forma consistente.',type:'definition'},
{kicker:'03 · Estructura',title:'Un sistema se construye por capas',body:'Los fundamentos alimentan componentes; los componentes forman patrones; los patrones construyen pantallas completas.',type:'layers'},
{kicker:'04 · Pieza fundamental',title:'¿Qué es un componente?',body:'Una pieza reutilizable de interfaz con estructura, apariencia y comportamiento definidos.',type:'component'},
{kicker:'05 · Reutilización',title:'Componente principal e instancia',body:'Una instancia no es una copia independiente: mantiene relación con la definición principal y puede conservar personalizaciones controladas.',type:'instance'},
{kicker:'06 · Flexibilidad',title:'Variantes y propiedades',body:'Un mismo componente puede representar múltiples posibilidades sin fragmentar el sistema en piezas independientes.',type:'variants'},
{kicker:'07 · Interacción',title:'Los componentes también tienen estados',body:'Default, hover, pressed, loading, success y disabled comunican qué está ocurriendo durante una interacción.',type:'states'},
{kicker:'08 · Composición',title:'Componentes dentro de componentes',body:'Las interfaces complejas pueden construirse combinando piezas cada vez más pequeñas y especializadas.',type:'nested'},
{kicker:'09 · Ejemplo real',title:'Construyamos una Sidebar reutilizable',body:'Una navegación completa puede construirse con instancias de Navigation Item y reutilizarse en todas las pantallas.',type:'sidebar'},
{kicker:'10 · Fundamentos',title:'Design Tokens',body:'En vez de repetir valores sueltos, el sistema utiliza nombres semánticos para color, espaciado, radios y tipografía.',type:'tokens'},
{kicker:'11 · Beneficio',title:'Consistencia',body:'Los mismos problemas deberían resolverse con las mismas reglas visuales y de comportamiento.',type:'consistency'},
{kicker:'12 · Beneficio',title:'Escalabilidad y mantenimiento',body:'Cuanto más crece el producto, más valioso se vuelve centralizar decisiones y reutilizar soluciones.',type:'scale'},
{kicker:'13 · Diferencia clave',title:'UI Kit ≠ Design System',body:'Un UI Kit es principalmente una colección visual. Un Design System agrega reglas, comportamiento, principios y documentación.',type:'uikit'},
{kicker:'14 · Uso correcto',title:'La documentación también forma parte del sistema',body:'No alcanza con tener componentes: hay que explicar cuándo usarlos, cómo combinarlos y qué decisiones representan.',type:'documentation'},
{kicker:'15 · Proceso',title:'Explorar → detectar patrón → sistematizar',body:'No todo debe convertirse inmediatamente en componente. Primero exploramos; después identificamos lo que realmente se repite.',type:'workflow'},
{kicker:'16 · Práctica',title:'Actividad: mini Design System para Aula Virtual',body:'El objetivo no será dibujar una pantalla: será construir las piezas necesarias para generar varias pantallas coherentes.',type:'practice'},
{kicker:'17 · Cierre',title:'De pantallas a sistemas',body:'El salto conceptual consiste en dejar de pensar solamente “¿cómo diseño esta pantalla?” y empezar a preguntar “¿qué reglas y componentes necesita mi sistema?”.',type:'summary'}]

function DemoButton({label='Guardar cambios',variant='primary'}:{label?:string,variant?:'primary'|'secondary'|'danger'}){
 const [s,setS]=useState<'idle'|'loading'|'done'>('idle')
 const click=()=>{if(s!=='idle')return;setS('loading');setTimeout(()=>setS('done'),900);setTimeout(()=>setS('idle'),2300)}
 return <motion.button whileHover={{y:-2,scale:1.015}} whileTap={{scale:.97}} onClick={click} className={`demo-button ${variant} ${s}`}><AnimatePresence mode="wait" initial={false}><motion.span key={s} initial={{opacity:0,y:5}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-5}} className="button-content">{s==='loading'&&<RefreshCw size={18} className="spin"/>}{s==='done'&&<Check size={18}/>} {s==='idle'?label:s==='loading'?'Guardando...':'Guardado'}</motion.span></AnimatePresence></motion.button>
}

function MiniApp({active}:{active:string}){const items=['Inicio','Materias','Calendario','Perfil'];return <div className="mini-app"><div className="mini-sidebar"><div className="mini-logo"><Blocks size={18}/> Aula</div>{items.map(i=><div key={i} className={`mini-nav ${active===i?'active':''}`}>{i}</div>)}</div><div className="mini-content"><div className="mini-topbar"/><div className="mini-grid"><div className="mini-panel large"/><div className="mini-panel"/><div className="mini-panel"/></div></div></div>}

function Visual({type}:{type:SlideType}){
 const [variant,setVariant]=useState<'primary'|'secondary'|'danger'>('primary');const [page,setPage]=useState('Inicio');const [linked,setLinked]=useState(false)
 if(type==='cover')return <div className="hero"><div className="orbit o1"/><div className="orbit o2"/><motion.div initial={{scale:.7,opacity:0}} animate={{scale:1,opacity:1}} className="core"><Blocks size={58}/><b>Design<br/>System</b></motion.div><motion.div initial={{x:-40,opacity:0}} animate={{x:0,opacity:1}} className="float f1"><Component/><span>Button</span></motion.div><motion.div initial={{x:40,opacity:0}} animate={{x:0,opacity:1}} className="float f2"><PanelLeft/><span>Sidebar</span></motion.div></div>
 if(type==='problem')return <div className="problem"><div className="screen-stack">{['Login','Dashboard','Materia','Perfil'].map((n,i)=><motion.div key={n} initial={{opacity:0,x:60}} animate={{opacity:1,x:i*18,y:i*14}} transition={{delay:i*.08}} className="fake-screen"><small>{n}</small><div className="fake-nav"/><div className="fake-btn" style={{width:100+i*8}}/></motion.div>)}</div><div className="bad"><X/><b>4 copias</b><span>4 lugares que mantener</span></div></div>
 if(type==='definition')return <div className="grid4">{[[<Palette/>,'Fundamentos','Color · tipo · espacio'],[<Component/>,'Componentes','Piezas reutilizables'],[<Workflow/>,'Patrones','Soluciones recurrentes'],[<Settings2/>,'Documentación','Reglas de uso']].map(([ic,n,d])=><motion.div whileHover={{y:-5}} className="card" key={n as string}><div className="icon">{ic}</div><b>{n}</b><span>{d}</span></motion.div>)}</div>
 if(type==='layers')return <div className="layers">{[['Foundations','Color · Type · Space'],['Components','Button · Input · Badge'],['Patterns','Login · Navigation · Cards'],['Screens','Dashboard · Course · Profile']].map(([a,b],i)=><motion.div initial={{opacity:0,y:25}} animate={{opacity:1,y:0}} transition={{delay:i*.1}} className="layer" style={{marginLeft:i*34}} key={a}><span>0{i+1}</span><div><b>{a}</b><small>{b}</small></div><ArrowRight/></motion.div>)}</div>
 if(type==='component')return <div className="center"><span className="chip"><Sparkles size={15}/> componente real</span><DemoButton/><p>Probá hover, click, loading y success.</p><div className="props"><span>Height 48</span><span>Radius 12</span><span>Padding 16</span><span>Type Primary</span></div></div>
 if(type==='instance')return <div className="center"><div className="master"><small>MAIN COMPONENT</small><DemoButton label="Button"/></div><ArrowRight className="down"/><div className="instances"><DemoButton label="Guardar"/><DemoButton label="Enviar"/><DemoButton label="Continuar"/></div><button className="ghost" onClick={()=>setLinked(!linked)}><Copy size={16}/>{linked?'Instancia vinculada':'Simular instancia'}</button></div>
 if(type==='variants')return <div className="center"><div className="segments">{(['primary','secondary','danger'] as const).map(v=><button key={v} onClick={()=>setVariant(v)} className={variant===v?'sel':''}>{v}</button>)}</div><DemoButton label="Acción" variant={variant}/><div className="props"><span>Component: Button</span><span>Type = {variant}</span></div></div>
 if(type==='states')return <div className="states">{[['Default',''],['Hover','hover'],['Pressed','pressed'],['Disabled','disabled']].map(([a,b])=><div className="state" key={a}><span>{a}</span><button className={`static ${b}`}>Guardar</button></div>)}<div className="state live"><span>Demo real</span><DemoButton label="Guardar"/></div></div>
 if(type==='nested')return <div className="nested"><div className="root">Course Card</div><div className="vline"/><div className="grid4">{[[<Palette/>,'Icon'],[<Type/>,'Text'],[<Layers3/>,'Badge'],[<Component/>,'Button']].map(([ic,n])=><div className="card small" key={n as string}><div className="icon">{ic}</div><b>{n}</b><span>instancia</span></div>)}</div></div>
 if(type==='sidebar')return <div className="sidebar-demo"><MiniApp active={page}/><div className="segments">{['Inicio','Materias','Calendario','Perfil'].map(x=><button className={page===x?'sel':''} onClick={()=>setPage(x)} key={x}>{x}</button>)}</div></div>
 if(type==='tokens')return <div className="tokens">{[['color.primary','#7C5CFF','violet'],['color.surface','#111827','surface'],['space.md','16px','space'],['radius.md','12px','radius']].map(([a,b,c],i)=><motion.div initial={{opacity:0,x:25}} animate={{opacity:1,x:0}} transition={{delay:i*.08}} className="token-row" key={a}><div className={`swatch ${c}`}/><div><b>{a}</b><span>{b}</span></div></motion.div>)}<p>Tokens → componentes → interfaz</p></div>
 if(type==='consistency')return <div className="compare"><div><h3>Con sistema</h3><DemoButton label="Guardar"/><DemoButton label="Continuar"/><DemoButton label="Enviar"/></div><div><h3>Sin sistema</h3><button className="odd a">Guardar</button><button className="odd b">Continuar</button><button className="odd c">Enviar</button></div></div>
 if(type==='scale')return <div className="center"><div className="scale-master"><Settings2/> Cambio en Button</div><div className="divider"/><div className="many">{Array.from({length:12}).map((_,i)=><motion.div initial={{scale:.7,opacity:0}} animate={{scale:1,opacity:1}} transition={{delay:i*.03}} key={i}>B{i+1}</motion.div>)}</div><p>1 definición · muchas instancias</p></div>
 if(type==='uikit')return <div className="uikit"><div className="kit"><Layers3/><h3>UI Kit</h3><span>Botones</span><span>Inputs</span><span>Cards</span></div><b>≠</b><div className="kit system"><Blocks/><h3>Design System</h3><span>Fundamentos</span><span>Reglas</span><span>Documentación</span></div></div>
 if(type==='documentation')return <div className="docs"><DemoButton label="Acción principal"/><div className="doc-sheet"><h3>Button / Primary</h3><p><Check/> Usar para la acción principal de un bloque.</p><p><X className="red"/> Evitar varios primarios compitiendo.</p><p><Settings2/> Definir estados y comportamiento.</p></div></div>
 if(type==='workflow')return <div className="flow">{[['Explorar',<Sparkles/>],['Detectar patrón',<Layers3/>],['Definir reglas',<Settings2/>],['Crear componente',<Component/>],['Reutilizar',<RefreshCw/>]].map(([n,ic],i)=><div className="flow-node" key={n as string}><div>{ic}</div><b>{n}</b>{i<4&&<ArrowRight/>}</div>)}</div>
 if(type==='practice')return <div className="practice"><div className="practice-card"><h3>Mini Design System</h3>{['Foundations','Button','Input','Badge','Navigation Item','Sidebar'].map(x=><p key={x}><Check/>{x}</p>)}</div><ArrowRight/><div className="screens"><span><LayoutDashboard/>Dashboard</span><span><Layers3/>Materia</span><span><Users/>Perfil</span></div></div>
 return <div className="summary"><div><small>Antes</small><b>Pantallas</b><span>copiar · pegar · corregir</span></div><motion.span animate={{x:[0,8,0]}} transition={{repeat:Infinity,duration:1.4}}><ArrowRight size={40}/></motion.span><div className="good"><small>Después</small><b>Sistema</b><span>definir · reutilizar · escalar</span></div></div>
}

const notes:Record<SlideType,string[]>={
cover:['Diseñar reglas antes que repetir dibujos.','Los ejemplos de la presentación son interactivos.'],problem:['Copiar y pegar crea objetos independientes.','El mantenimiento se vuelve más costoso a medida que el producto crece.'],definition:['Un Design System combina reglas visuales y de comportamiento.','No es solamente una biblioteca de botones.'],layers:['Foundations → Components → Patterns → Screens.','Cada nivel reutiliza decisiones de niveles anteriores.'],component:['Un componente posee una definición reutilizable.','Su comportamiento también puede formar parte del diseño.'],instance:['La instancia mantiene vínculo conceptual con el componente principal.','Puede personalizar contenido sin dejar de pertenecer al sistema.'],variants:['Una variante representa otra posibilidad del mismo componente.','Conviene separar propiedades como Type, Size y State.'],states:['Los estados comunican qué está ocurriendo.','Feedback y componentes interactivos están directamente relacionados.'],nested:['Un componente puede usar instancias de otros componentes.','Así se construyen jerarquías más complejas.'],sidebar:['La Sidebar reutiliza Navigation Items.','La propiedad Page cambia la sección activa.'],tokens:['Los tokens convierten valores en decisiones semánticas.','color.primary comunica intención mejor que repetir un hexadecimal.'],consistency:['Consistencia es resolver problemas similares con reglas similares.','No significa que todas las pantallas sean idénticas.'],scale:['El sistema aumenta su valor cuando el producto crece.','Una modificación central puede beneficiar muchas instancias.'],uikit:['Un UI Kit puede formar parte de un Design System.','El sistema agrega criterios, comportamiento y documentación.'],documentation:['La documentación explica cuándo y por qué usar una pieza.','Sin reglas de uso, una colección puede seguir siendo ambigua.'],workflow:['No todo debe convertirse inmediatamente en componente.','Primero exploramos; sistematizamos cuando aparece un patrón estable.'],practice:['Primero se construyen piezas, luego pantallas.','La pantalla final es una composición del sistema.'],summary:['El cambio de mentalidad es pasar de “hacer pantallas” a “construir un sistema”.','Reutilización, mantenimiento y escalabilidad son consecuencias de ese enfoque.']}

export default function App(){
 const [i,setI]=useState(0),[dir,setDir]=useState(1),[full,setFull]=useState(false);const s=slides[i];const progress=useMemo(()=>((i+1)/slides.length)*100,[i]);
 const go=(n:number)=>{const x=Math.max(0,Math.min(slides.length-1,n));setDir(x>=i?1:-1);setI(x)}
 const fullToggle=async()=>{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen()}
 useEffect(()=>{const h=()=>setFull(!!document.fullscreenElement);document.addEventListener('fullscreenchange',h);return()=>document.removeEventListener('fullscreenchange',h)},[])
 useEffect(()=>{const h=(e:KeyboardEvent)=>{if(['ArrowRight','PageDown',' '].includes(e.key)){e.preventDefault();go(i+1)}if(['ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();go(i-1)}if(e.key==='Home')go(0);if(e.key==='End')go(slides.length-1);if(e.key.toLowerCase()==='f')fullToggle()};window.addEventListener('keydown',h);return()=>window.removeEventListener('keydown',h)},[i])
 return <main className="presentation"><div className="ambient a"/><div className="ambient b"/><header><div className="brand"><div className="mark"><Blocks/></div><div><b>Interfaz de Usuario</b><span>Design Systems · Clase interactiva</span></div></div><div className="actions"><b>{String(i+1).padStart(2,'0')} / {slides.length}</b><button onClick={fullToggle}>{full?<Minimize2/>:<Expand/>}</button></div></header><div className="progress"><motion.div animate={{width:`${progress}%`}}/></div><section className="stage"><AnimatePresence mode="wait" custom={dir}><motion.article key={i} custom={dir} variants={{enter:(d:number)=>({opacity:0,x:d*70,scale:.985}),center:{opacity:1,x:0,scale:1},exit:(d:number)=>({opacity:0,x:d*-60,scale:.985})}} initial="enter" animate="center" exit="exit" transition={{duration:.4}} className="slide"><div className="copy"><span className="kicker">{s.kicker}</span><h1>{s.title}</h1><p className="lead">{s.body}</p><div className="notes">{notes[s.type].map(n=><p key={n}><Check/>{n}</p>)}</div></div><div className="visual"><Visual type={s.type}/></div></motion.article></AnimatePresence></section><footer><button onClick={()=>go(i-1)} disabled={i===0}><ArrowLeft/>Anterior</button><div className="dots">{slides.map((_,x)=><button key={x} onClick={()=>go(x)} className={x===i?'active':''}/>)}</div><button onClick={()=>go(i+1)} disabled={i===slides.length-1}>Siguiente<ArrowRight/></button></footer></main>
}
